services:
  _template: &template
    build:
      context: ../
      dockerfile: e2e/___template__.Dockerfile
    working_dir: /test
    volumes:
      - ../:/test:ro
      - ../../config/:/repo:ro

  alpine:
    <<: *template
    build:
      context: ../
      dockerfile: e2e/alpine.Dockerfile

  archlinux:
    <<: *template
    build:
      context: ../
      dockerfile: e2e/archlinux.Dockerfile

  debian:
    <<: *template
    build:
      context: ../
      dockerfile: e2e/debian.Dockerfile

  fedora:
    <<: *template
    build:
      context: ../
      dockerfile: e2e/fedora.Dockerfile

  rocky:
    <<: *template
    build:
      context: ../
      dockerfile: e2e/rocky.Dockerfile

  oraclelinux:
    <<: *template
    build:
      context: ../
      dockerfile: e2e/oraclelinux.Dockerfile
